### ISSUE TITLE
Needs update

### ISSUE THREAD

**Issue by GuguRD** [humhub/humhub-modules-translation#15]
I updated to lastest HumHub version 1.2-beta1 and this module stopped working. It was quite ok before... =(

Any help on making it work again?

**Comment by franciscoguerrero** [comment]
It happened to me too. The problem seems to be in the construction of the link. See how it add an "?" in the image below:
<img width="520" alt="captura de pantalla 2017-03-15 a las 00 15 29" src="https://cloud.githubusercontent.com/assets/573775/23935921/90d0d856-0914-11e7-9b04-b5227f1ab9aa.png">

If you change that "?" for a "&" you'll be able to open the file.

The problem is still that when you hit the Save button, it will trigger the wrong link again, so you won't be able to save your changes. I haven't found where that link is built on the script.

**Comment by franciscoguerrero** [comment]
I found the form action link in /assets/js/translation.js and I changed the way it builds the link but still  not working...

**Comment by GuguRD** [comment]
Thanks for this, it fixed the problem. You should make a Pull Request...

=)

**Comment by franciscoguerrero** [comment]
Thank you! I guess you're running on development mode, you will have to change back that line when you're ready to run your website in production. Good luck and you're welcome! 👍

**Comment by GuguRD** [comment]
This fix isn't working anymore, I will try again looking on this... but I am totally noob. rsrs
