### ISSUE TITLE
Could not translate text

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-modules-translation#40]
When copy 1:1 original text to the translated value, following error appears:
![image](https://user-images.githubusercontent.com/4736168/108210189-82fbbb00-712b-11eb-8620-6bf96d6f685b.png)

See also:
https://translate.humhub.org/content/perma?id=19015

**Comment by ArchBlood** [comment]
The issue seems to be here

https://github.com/humhub/humhub-modules-twofa/blob/master/views/config/userGoogleAuthenticatorCode.php#L18

Should look like this :thinking:
```php
['docLinkAttrs' => ' href="https://support.google.com/accounts/answer/1066447" target="_blank"']); ?></p>
```

**Comment by yurabakhtin** [comment]
@luke- I have investigated the problem in that I created a not allowed text for translation `<a{docLinkAttrs}>Google Authenticator</a>`, because on save the entered translation text is processed by this code https://github.com/humhub/humhub-modules-translation/blob/master/models/TranslationLog.php#L208 `$translationPurified = TranslationPurifier::process($this->translation);` so the text is converted into `<a{docLinkAttrs}>Google Authenticator</a>`.

I think to change the original text in 2FA module to new: `'Install an application that implements a time-based one-time password (TOTP) algorithm, such as <a href="{docUrl}" target="_blank">Google Authenticator</a>, and use it to scan the QR code shown below.'` but please see there we need `target="_blank"` and I am not sure it is supported because here https://github.com/humhub/humhub-modules-translation/blob/master/models/parser/TranslationPurifier.php#L19 it seems only attribute `href` is supported for `<a>`.

**Comment by luke-** [comment]
@yurabakhtin Thank you for the analysis. We should probably then change the link as suggested. I would suggest we add the target argument to the Purifier, what do you think?

**Comment by buddh4** [comment]
Can't we just replace the whole link, I think the link does not need to be translated?

**Comment by yurabakhtin** [comment]
@buddh4 I have replaced the whole link in PR https://github.com/humhub/humhub-modules-twofa/pull/15 because currently the attribute `target` is not supported yet by this module:

<img width="613" alt="target_not_supported" src="https://user-images.githubusercontent.com/6995524/108310228-184a8e00-71c4-11eb-8514-cc638a3b2a4b.png">

Let me know if I should modify this module in order to support `target`, but I think translators should not think about such data as link attributes and maybe better to replace whole link, but of course sometimes better to know a text of a link because it may be an important part of the translatable phrase.

**Comment by luke-** [comment]
@yurabakhtin Thanks for the PR and yes, please add the `target` support to the purifier here.

**Comment by yurabakhtin** [comment]
@luke- 

> please add the `target` support to the purifier here.

PR https://github.com/humhub/humhub-modules-translation/pull/43

@buddh4 

> `_blank` links should also add `noopener nofollow` which I think is done by the prufyer automatically if you add and allow `target="_blank"`

You are right partly because it adds `noreferrer noopener` for any value inside the attribute `target`:

<img width="604" alt="target" src="https://user-images.githubusercontent.com/6995524/108339368-62de0180-71e8-11eb-8cb7-9410f8f4b7b4.png">

**Comment by buddh4** [comment]
In which cases is the translation of such links not possible? I think only if you need to require a language specific url? If you need to translate the link text you can always do something like this:

```
Yii::t('MyModule.base','This is a {link}', [
  'link' => Html::a(Yii::t('MyModule.base', 'Link text', ...)
])
```

**Comment by yurabakhtin** [comment]
@buddh4 Yes I agree with you that firstly translators should not be familiar with html. So if it is enough I will use only `{link}` instead of html tags in translatable strings for all strings in my future code.
But by this way translations will not be ideal for some languages like my because one word may has several forms depending on context.

**Comment by buddh4** [comment]
You mean the seperation of `Link text` and `This is a {link}` is may confusing in some languages, since the translator does not know those two texts are related?

**Comment by yurabakhtin** [comment]
@buddh4 

> You mean the seperation of `Link text` and `This is a {link}` is may confusing in some languages, since the translator does not know those two texts are related?

Yes.

**Comment by buddh4** [comment]
Maybe we should find a best practice pattern for the translation categories as:

- base
- configuration
- stream
- ...

In the past we had an almost file based category seperation, which was too much seperation, then migrated to an almost `base` category only approach. I think need a guideline when to use which category and when to create a new category, if for example the `This is a {link}` example would be used only in the module configuration, it should not be too hard to find the right place if we have a `configuration` translation category for this module.
